apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: suptc-ingress
  namespace: suptc
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: app.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: suptc-frontend
                port:
                  number: 80
    - host: api.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: suptc-api
                port:
                  number: 8000
